/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef cassandra_CONSTANTS_H
#define cassandra_CONSTANTS_H

#include "cassandra_types.h"
#include <string>

namespace org { namespace apache { namespace cassandra {

class cassandraConstants {
 public:
  cassandraConstants();

  std::string CASSANDRA_API_VERSION;
};

extern const cassandraConstants g_cassandra_constants;

}}} // namespace

#endif
